# Site settings
title: Wikilearn Foundation
email: info@wikilearnfoundation.org
description: > # this means to ignore newlines until "baseurl:"
  Projects in progress
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wikilearnfoundation.org" # the base hostname & protocol for your site
github_username:  explodingllama

# Build settings
markdown: kramdown
